@routeURL = http://localhost:5194

GET {{User_service_HostAddress}}/weatherforecast/
Accept: application/json

### 
GET {{routeURL}}/api/User
Accept: application/json

### 

POST {{routeURL}}/api/User/register
Content-Type: application/json
{
  "NomUser": "MohammedX23DEV",
  "Email": "mohammed@gmail.com",
  "MotPasse": "12345",
  "Role": 1,
}

###

POST {{routeURL}}/api/User/login
Content-Type: application/json
{
  "Email": "achraf@gmail.com",
  "MotPasse": "12345"
}

###

GET {{routeURL}}/api/User/auth
Accept: application/json