@routeURL = http://localhost:5194

GET {{User_service_HostAddress}}/weatherforecast/
Accept: application/json

### 
GET {{routeURL}}/api/User
Accept: application/json

### 

POST {{routeURL}}/api/User/register
Content-Type: application/json
{
  "NomUser": "samsssS",
  "Email": "samas@gmail.m",
  "MotPasse": "samado"
}

###

POST {{routeURL}}/api/User/login
Content-Type: application/json
{
  "Email": "samas@gmail.com",
  "MotPasse": "samado"
}

###

GET {{routeURL}}/api/User/auth
Accept: application/json